
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'E. B. White', 'Charlotte''s Web', '059030271X');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'Piano Lessons Can Be Murder (Goosebumps, No 13)', '590494481');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'K.A. Applegate', 'The Reaction (Animorphs, No 12)', '590997343');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Anne Rivers Siddons', 'Fault Lines', '61093343');
INSERT INTO public.books ( author, name, serialnumber) VALUES ('R. L. Stine', 'Phantom of the Auditorium (Goosebumps, No 24)', '590483544');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Jean M. Auel', 'MAMMOTH HUNTERS,THE (Auel, Jean M. , Earth''s Children.)', '553260960');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Rebecca Wells', 'Divine Secrets of the Ya-Ya Sisterhood: A Novel', '60173289');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'Night of the Living Dummy II  (Goosebumps, No 31)', '590483498');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Dean Koontz', 'Midnight', '425194515');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'You Can''t Scare Me! (Goosebumps, No 15)', '590494503');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'The Abominable Snowman of Pasadena (Goosebumps, No 38)', '590568752');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'E. B. White', 'Charlotte''s Web (Trophy Newbery)', '64400557');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Scott O''Dell', 'Island of the Blue Dolphins', '440439884');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Claudia and the New Girl (Baby-Sitters Club, 12)', '590251678');
INSERT INTO public.books ( author, name, serialnumber) VALUES ('C. S. Lewis', 'The Magician''s Nephew (The Chronicles of Narnia)', '64471101');
INSERT INTO public.books ( author, name, serialnumber) VALUES ('Kevin Anderson', 'Jedi Search (Star Wars: The Jedi Academy Trilogy, Vol. 1)', '553297988');
INSERT INTO public.books ( author, name, serialnumber) VALUES ('Scott O''Dell', 'Island of the Blue Dolphins', '440940001');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Amanda Quick', 'The River Knows', '515144363');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Nora Roberts', 'Remember When', '425195473');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Jerry B. Jenkins', 'Facing the Future (Left Behind: The Kids #4)', '842321969');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Jerry B. Jenkins', 'Nicolae High (Left Behind: The Kids #5)', '842343253');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'C. S. Lewis', 'The Magician''s Nephew', '20442300');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'The Barking Ghost (Goosebumps, No 32)', '590483447');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Dawn''s Wicked Stepsister (Baby-Sitters Club, 31)', '590424971');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Kimberly Willis Holt', 'My Louisiana Sky', '440415705');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Nora Roberts', 'Waiting for Nick / Considering Kate (Stanislaski, Books 5 & 6) (Stanislaski Stories)', '037328568X');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Judy Blume', 'Otherwise Known as Sheila the Great', '440467012');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Bsc #04: Mary Anne Saves The Day (Baby-Sitters Club: Collector''s Edition)', '590251597');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Mary Anne Saves the Day (Baby-Sitters Club, 4)', '590435124');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'The Ghost at Dawn''s House (The Baby-Sitters Club #9)', '590435086');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Karens Prize (Baby-Sitters Little Sister, 11)', '590436503');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Jack Canfield', 'Chicken Soup for the Preteen Soul - 101 Stories of Changes, Choices', '1558748008');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'K.A. Applegate', 'Animorphs Megamorphs #01: The Andalite''s Gift (Animorphs)', '590213040');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'Return of the Mummy (Goosebumps, No 23)', '590477455');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Baby-sitters Little Sister #1:  Karen''s Witch', '590443003');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Rick Warren', 'The Purpose-Driven Life: What on Earth Am I Here For?', NULL);
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Patricia Gaffney', 'Circle of Three: A Novel', '61098361');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'V.C. Andrews', 'Into the Garden (Wildflowers)', '671007718');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'John Grisham', 'PLAYING FOR PIZZA', '440244714');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'Welcome to Camp Nightmare (Goosebumps, No 9)', '590466194');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'K.A. Applegate', 'The Warning (Animorphs, No. 16)', '590494309');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'jeffrey archer', 'A Twist in the Tale', '340493534');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Lynne Reid Banks', 'The Secret of the Indian (Indian in the Cupboard)', '380710404');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R. L. Stine', 'Be Careful What You Wish For... (Goosebumps, No 12)', '590494473');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'R.L. Stine', 'Broken Hearts (Fear Street Superchiller)', '671786091');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Karen''s Roller Skates (Baby-Sitters Little Sister #2)', '590442597');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Karen''s Grandmothers (Baby-Sitters Little Sister, 10)', '590436511');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Ann M. Martin', 'Karen''s Haircut (Baby-Sitters Little Sister (Paperback))', '590426702');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Mildred D. Taylor', 'Roll of Thunder, Hear My Cry', '014034893X');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'John Cassidy', 'Juggling for the Complete Klutz', '932592007');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Jules Verne', 'Hai vạn dặm dưới đáy biển',  '122592007');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Robert van Gulik', 'Thi nhân và sát nhân',  '132592007');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Robert van Gulik', 'Bí mật căn phòng đỏ',  '142592007');
INSERT INTO public.books ( author, name, serialnumber) VALUES ( 'Carolina Zanotti', '.',  '8398622550051');
